function [scenario, egoVehicle] = createDrivingScenario()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.12 (R2022a) and Automated Driving Toolbox 3.5 (R2022a).
% Generated on: 18-Aug-2022 01:13:35

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [40.8 94.3 0;
    -102.5 90.8 0;
    -133.1 -4.3 0;
    48.4 -104.7 0;
    40.8 94.3 0];
laneSpecification = lanespec(3, 'Width', 11.95);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road');

% Add the actors
car = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-48.8 105.3 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'PlotColor', [255 255 17] / 255, ...
    'Name', 'Car');
waypoints = [-41.7 105.3 0;
    -23 105.3 0;
    17.3 93.6 0;
    38.4 83.7 0;
    61.8 73.1 0;
    88.1 35.7 0;
    97.5 -11.7 0;
    90.5 -50.9 0;
    77 -72.5 0;
    56 -86.6 0;
    34.9 -98.9 0;
    3.3 -110 0;
    -26 -109.4 0;
    -71.6 -89.5 0;
    -107.9 -49.7 0;
    -127.8 -23.4 0;
    -133 8.8 0;
    -127.2 46.2 0;
    -110.8 83.1 0;
    -84.5 104.2 0];
speed = [30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30];
trajectory(car, waypoints, speed);

truck = vehicle(scenario, ...
    'ClassID', 2, ...
    'Length', 8.2, ...
    'Width', 2.5, ...
    'Height', 3.5, ...
    'Position', [-21.3 104.7 0], ...
    'Mesh', driving.scenario.truckMesh, ...
    'PlotColor', [255 105 41] / 255, ...
    'Name', 'Truck');
waypoints = [-21.3 104.7 0;
    8 97.7 0;
    21.4 90.7 0;
    41.3 77.2 0;
    61.8 57.3 0;
    78.2 28.7 0;
    86.4 -17 0;
    75.9 -57.3 0;
    60.1 -77.8 0;
    39.6 -96.5 0;
    14.4 -109.4 0;
    -3.7 -121.7 0;
    -22.4 -121.7 0;
    -47.6 -114.7 0;
    -71.6 -88.9 0;
    -96.2 -64.9 0;
    -116.6 -31.6 0;
    -121.9 7 0;
    -116.6 46.8 0;
    -95.6 79 0;
    -76.9 93.6 0];
speed = [30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30];
trajectory(truck, waypoints, speed);

% Add the ego vehicle
car2 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-49.3 117.5 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'PlotColor', [0 114 189] / 255, ...
    'Name', 'Car1');
waypoints = [-49.3 117.5 0;
    -18.9 117 0;
    25 103 0;
    48.4 90.7 0;
    67.7 80.8 0;
    81.7 68.5 0;
    96.9 43.3 0;
    108 1.8 0;
    105.7 -38 0;
    94 -70.8 0;
    81.1 -89.5 0;
    66.5 -102.4 0;
    48.4 -109.4 0;
    17.9 -119.9 0;
    -0.2 -122.9 0;
    -38.2 -118.8 0;
    -66.9 -107.6 0;
    -99.7 -81.3 0;
    -118.4 -60.8 0;
    -137.1 -39.2 0;
    -144.7 -14 0;
    -143 18.7 0;
    -130.1 43.3 0;
    -114.9 77.2 0;
    -96.7 97.1 0;
    -74.5 108.8 0];
speed = [30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30];
trajectory(car2, waypoints, speed);

egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-43.7999349517335 130.125683845979 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car2');
waypoints = [-56.4 129.3 0;
    -29.5 130.5 0;
    5.1 125.2 0;
    30.2 114.1 0;
    51.9 100.1 0;
    70.6 81.9 0;
    78.2 69 0;
    83.5 50.3 0;
    90.5 26.3 0;
    94 7 0;
    89.3 -15.8 0;
    85.8 -33.9 0;
    78.2 -55.6 0;
    76.4 -81.3 0;
    74.1 -94.8 0;
    60.6 -108.2 0;
    38.4 -123.4 0;
    20.3 -129.9 0;
    -1.4 -133.4 0;
    -30.6 -131.6 0;
    -68.1 -122.3 0;
    -103.2 -95.9 0;
    -130.7 -59.7 0;
    -145.9 -5.3 0;
    -141.8 39.8 0;
    -122.5 88.9 0;
    -94.4 114.1 0;
    -68.7 124.6 0];
speed = [30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30];
trajectory(egoVehicle, waypoints, speed);